name: Create release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 1.1.2307.2711)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
      
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
       
    - name: Update config.dev.json
      uses: jossef/action-set-json-field@v2.1
      with:
        file: at.D365.PowerCID.Portal/ClientApp/src/assets/config/config.dev.json
        field: version
        value: "${{ github.event.inputs.versionName }}"
        
    - name: Update config.prod.json
      uses: jossef/action-set-json-field@v2.1
      with:
        file: at.D365.PowerCID.Portal/ClientApp/src/assets/config/config.prod.json
        field: version
        value: "${{ github.event.inputs.versionName }}"
        
    - name: Update package.json
      uses: jossef/action-set-json-field@v2.1
      with:
        file: at.D365.PowerCID.Portal/ClientApp/package.json
        field: version
        value: "${{ github.event.inputs.versionName }}"
        
    - name: Update at.D365.PowerCID.Portal.csproj
      uses: MathieuSoysal/replace-string-in-file@v1.0.0
      with:
        file: at.D365.PowerCID.Portal/at.D365.PowerCID.Portal.csproj
        old-string: '<Version>.+<\/Version>'
        new-string: <Version>${{ github.event.inputs.versionName }}</Version>
        
    - name: Update at.D365.PowerCID.Portal.csproj
      uses: Mudlet/xmlstarlet-action@master
      with:
        args: ed -O -P --inplace -u "/Project/PropertyGroup/Version" -v "${{ github.event.inputs.versionName }}" at.D365.PowerCID.Portal/at.D365.PowerCID.Portal.csproj
        
    - name: Commit and push files
      run: |
        git add -A
        git commit -m "stamp v${{ github.event.inputs.versionName }}"
        git push --set-upstream origin release/v${{ github.event.inputs.versionName }}
